# -*- coding: utf-8 -*-
"""store_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFbwRtZSEeJohEgIbGqdv_vmwbB97URU
"""

# !pip install wordcloud

# # ✅ 1️⃣ 나눔고딕 폰트 설치
# !apt-get update -qq
# !apt-get install -qq fonts-nanum

# # ✅ 2️⃣ matplotlib 폰트 캐시 삭제
# !rm -rf /root/.cache/matplotlib

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import seaborn as sns
import os

# 폰트 경로 직접 지정
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'

if os.path.exists(font_path):
    fm.fontManager.addfont(font_path)
    plt.rcParams['font.family'] = 'NanumGothic'
    plt.rcParams['axes.unicode_minus'] = False
    print("✅ 한글 폰트 적용 완료:", font_path)
else:
    print("❌ NanumGothic.ttf 파일을 찾을 수 없습니다. 설치 확인 필요")

import pandas as pd
import numpy as np
from wordcloud import WordCloud
import seaborn as sns
import re

from google.colab import drive
drive.mount('/content/drive')

"""## 식당데이터

### 데이터 탐색
"""

restaurant_df = pd.read_csv("/content/drive/MyDrive/Ehwa/캡스톤/1.id_v2.csv")

print(restaurant_df.shape)
print(restaurant_df.info())
restaurant_df.head(5)

# 중복 확인
print(restaurant_df['id'].duplicated().sum())
print(restaurant_df['name'].duplicated().sum())

# 결측치 확인
restaurant_df.isna().sum()

restaurant_df['unique_key'] = restaurant_df['name'] + '_' + restaurant_df['address']
restaurant_df['unique_key'].duplicated().sum()

from geopy.distance import geodesic

# ✅ 각 역의 위도, 경도, 반경(미터)
stations = {
    '서울숲역': {'coord': (37.5444, 127.0443), 'radius': 700},
    '성수역': {'coord': (37.5446, 127.0565), 'radius': 700},
    '건대입구역': {'coord': (37.5404, 127.0690), 'radius': 700}
}

# ✅ 각 식당의 좌표 기준으로 가장 가까운 역 찾기
def classify_region(row):
    point = (row['lat'], row['lon'])
    min_dist = float('inf')
    region = '기타'

    for name, info in stations.items():
        dist = geodesic(point, info['coord']).m  # 미터 단위 거리
        if dist < min_dist:
            min_dist = dist
            region = name

    # ✅ 각 역 고유 반경 기준으로 판별
    if min_dist <= stations[region]['radius']:
        return region
    else:
        return '기타'

# ✅ 적용
restaurant_df['region'] = restaurant_df.apply(classify_region, axis=1)

# ✅ 결과 확인
region_counts = restaurant_df['region'].value_counts()
print(region_counts)

import matplotlib.pyplot as plt
import seaborn as sns

# 데이터 준비
region_counts = restaurant_df['region'].value_counts()
values = region_counts.values
labels = region_counts.index
ratios = (values / values.sum() * 100).round(1)

# 비율(값)에 따라 색상 진하기 조절
norm = (values - values.min()) / (values.max() - values.min())
colors = [sns.color_palette("Greens", 100)[int(30 + n * 60)] for n in norm]

# autopct 함수: 비율 + 개수 함께 표시
def make_autopct(values):
    def my_autopct(pct):
        total = sum(values)
        count = int(round(pct * total / 100.0))
        return f'{pct:.1f}%'
    return my_autopct

# 시각화
plt.figure(figsize=(7,7))
wedges, texts, autotexts = plt.pie(
    values,
    labels=labels,
    autopct=make_autopct(values),
    startangle=90,
    colors=colors,
    pctdistance=0.8,
    labeldistance=1.1,
    wedgeprops={'edgecolor':'white', 'linewidth':1.5}
)

# 라벨과 퍼센트 글씨체 조정
for text in texts:
    text.set_fontsize(12)
    text.set_fontweight('bold')
for autotext in autotexts:
    autotext.set_fontsize(11)
    autotext.set_color('black')

plt.title('700m 반경 내 식당 비율 및 개수', fontsize=15, fontweight='bold', pad=20)
plt.tight_layout()
plt.show()

import folium

folium_map = folium.Map(location=[37.545, 127.043], zoom_start=13)

for _, row in restaurant_df.dropna(subset=['lat','lon']).iterrows():
    folium.CircleMarker(
        location=[row['lat'], row['lon']],
        radius=2,
        color='green',
        fill=True,
        fill_opacity=0.5
    ).add_to(folium_map)

folium_map.save('/content/drive/MyDrive/Ehwa/캡스톤/restaurant_map.html')

def normalize_category(cat):
    if pd.isna(cat):
        return '기타'
    cat = str(cat).strip()

    # 대표 카테고리 규칙
    if '한식' in cat or '국밥' in cat or '백반' in cat:
        return '한식'
    elif '중식' in cat or '중국' in cat or '짜장' in cat:
        return '중식'
    elif '일식' in cat or '초밥' in cat or '돈카츠' in cat or '일본' in cat:
        return '일식'
    elif '카페' in cat or '디저트' in cat or '커피' in cat:
        return '카페'
    elif '분식' in cat or '떡볶이' in cat or '김밥' in cat:
        return '분식'
    elif '양식' in cat or '스테이크' in cat or '이탈' in cat or '피자' in cat or '파스타' in cat:
        return '양식'
    elif '아시아' in cat or '태국' in cat or '베트남' in cat:
        return '아시안'
    elif '패스트' in cat or '버거' in cat:
        return '패스트푸드'
    elif '고기' in cat or '삼겹' in cat or '소고기' in cat or '돼지' in cat:
        return '고기/구이'
    elif '술' in cat or '포차' in cat or '주점' in cat or '바' in cat:
        return '주점'
    else:
        return '기타'

restaurant_df['category_clean'] = restaurant_df['category_1'].apply(normalize_category)
top_categories = restaurant_df['category_clean'].value_counts().head(15)

plt.figure(figsize=(9,6))
ax = sns.barplot(
    x=top_categories.values,
    y=top_categories.index,
    color='#006400'  # 진한 초록색
)

plt.title('상위 15개 카테고리별 식당 수', fontsize=14, weight='bold')
plt.xlabel('식당 수', fontsize=12)
plt.ylabel('카테고리', fontsize=12)

# 비율 계산
category_ratio = (top_categories / top_categories.sum() * 100).round(1)

# ✅ 개수 + 비율을 같이 표시
for i, (v, r) in enumerate(zip(top_categories.values, category_ratio.values)):
    ax.text(v + 10, i, f'{v} ({r}%)', color='black', va='center', fontsize=11)

plt.tight_layout()
plt.show()

# region_counts = restaurant_df['region'].value_counts()
# sns.barplot(x=region_counts.values, y=region_counts.index, palette="Greens_r")
# plt.title("700m 반경 내 지역별 식당 수", fontsize=14, fontweight="bold")
# plt.xlabel("식당 수"); plt.ylabel("지역")

# ratio = (region_counts / region_counts.sum() * 100).round(1)
# for i, (v, r) in enumerate(zip(region_counts.values, ratio.values)):
#     plt.text(v + 10, i, f"{v}개 ({r}%)", va='center', fontsize=10)
# plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(pivot.T, annot=True, fmt='.1f', cmap='Greens', cbar_kws={'label':'비율(%)'})
plt.title('지역별 업종 비율 히트맵', fontsize=14, fontweight='bold')
plt.xlabel('지역')
plt.ylabel('업종')
plt.tight_layout()
plt.show()

from math import pi

categories = list(pivot.columns)
num_categories = len(categories)

for region in pivot.index:
    values = pivot.loc[region].tolist()
    values += values[:1]  # 닫기용
    angles = [n / float(num_categories) * 2 * pi for n in range(num_categories)]
    angles += angles[:1]

    plt.polar(angles, values, label=region)

plt.xticks([n / float(num_categories) * 2 * pi for n in range(num_categories)], categories, fontsize=9)
plt.title('지역별 업종 비율 비교 (Radar Chart)', fontsize=14, fontweight='bold')
plt.legend(bbox_to_anchor=(1.05,1), loc='upper left')
plt.show()



"""## 리뷰데이터"""

review_df = pd.read_csv("/content/drive/MyDrive/Ehwa/캡스톤/4. review_kakaogoogle_정화.csv")

print(review_df.shape)
print(review_df.info())
review_df.head(5)

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

plt.figure(figsize=(8,5))
sns.histplot(review_df['rating'], bins=np.arange(0.5, 5.6, 1), kde=True,
             color='#2E8B57', edgecolor='black', alpha=0.6)

mean_rating = review_df['rating'].mean()
plt.axvline(mean_rating, color='red', linestyle='--', linewidth=2)
plt.text(mean_rating+0.1, 6000, f'평균 {mean_rating:.2f}점', color='red', fontsize=12)
plt.title('리뷰 평점의 분포', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('평점', fontsize=12)
plt.ylabel('리뷰 개수', fontsize=12)
plt.xticks([1,2,3,4,5], ['1점', '2점', '3점', '4점', '5점'])

counts = review_df['rating'].value_counts(normalize=True).sort_index()
for rating, ratio in counts.items():
    plt.text(rating, ratio * len(review_df) + 300, f'{ratio*100:.1f}%',
             ha='center', va='bottom', fontsize=10, color='black')

plt.tight_layout()
plt.show()

from datetime import datetime, timedelta

# 구글 상대적 날짜를 실제 날짜로 변환하는 함수
def convert_google_relative_date(relative_date_str, reference_date="2025-10-18"):
    if pd.isna(relative_date_str):
        return None

    try:
        relative_date_str = str(relative_date_str).strip()
        ref_date = datetime.strptime(reference_date, '%Y-%m-%d')

        import re

        year_match = re.search(r'(\d+)년\s*전', relative_date_str)
        if year_match:
            years = int(year_match.group(1))
            actual_date = ref_date - timedelta(days=years * 365)
            return actual_date.strftime('%Y-%m-%d')
        month_match = re.search(r'(\d+)달\s*전', relative_date_str)
        if month_match:
            months = int(month_match.group(1))
            # 대략적으로 1달 = 30일로 계산
            actual_date = ref_date - timedelta(days=months * 30)
            return actual_date.strftime('%Y-%m-%d')
        week_match = re.search(r'(\d+)주\s*전', relative_date_str)
        if week_match:
            weeks = int(week_match.group(1))
            actual_date = ref_date - timedelta(weeks=weeks)
            return actual_date.strftime('%Y-%m-%d')
        day_match = re.search(r'(\d+)일\s*전', relative_date_str)
        if day_match:
            days = int(day_match.group(1))
            actual_date = ref_date - timedelta(days=days)
            return actual_date.strftime('%Y-%m-%d')
        if '어제' in relative_date_str:
            actual_date = ref_date - timedelta(days=1)
            return actual_date.strftime('%Y-%m-%d')
        if '오늘' in relative_date_str:
            return ref_date.strftime('%Y-%m-%d')
        if '.' in relative_date_str or '-' in relative_date_str:
            if '.' in relative_date_str:
                return datetime.strptime(relative_date_str, '%Y.%m.%d').strftime('%Y-%m-%d')
            elif '-' in relative_date_str:
                return datetime.strptime(relative_date_str, '%Y-%m-%d').strftime('%Y-%m-%d')

        return None

    except:
        return None

print("구글 상대적 날짜 변환 함수 정의 완료")

# 날짜 계산 함수 (구글/카카오 구분) - 실제 날짜로 변환
def convert_to_actual_date(date_str, site, reference_date="2025-10-18"):
    """
    날짜를 실제 날짜로 변환하여 반환
    구글의 경우 상대적 날짜를 먼저 실제 날짜로 변환
    """
    if pd.isna(date_str):
        return None

    try:
        if site == 'google':
            actual_date_str = convert_google_relative_date(date_str, reference_date)
            if actual_date_str is None:
                return None
            return actual_date_str
        else:
            date_str_clean = str(date_str).strip()
            if date_str_clean.endswith('.'):
                date_str_clean = date_str_clean[:-1]

            if '.' in date_str_clean:
                date_obj = datetime.strptime(date_str_clean, '%Y.%m.%d')
                return date_obj.strftime('%Y-%m-%d')
            elif '-' in date_str_clean:
                date_obj = datetime.strptime(date_str_clean, '%Y-%m-%d')
                return date_obj.strftime('%Y-%m-%d')
            else:
                return None

    except:
        return None

print("수정된 날짜 변환 함수 정의 완료")

review_df['actual_date'] = review_df.apply(lambda row: convert_to_actual_date(row['date'], row['site']), axis=1)

review_df.head(5)

review_df['actual_date'] = pd.to_datetime(review_df['actual_date'])
review_df.groupby(review_df['actual_date'].dt.to_period('M')).size().plot()

restaurant_df['length'] = restaurant_df['review'].str.len()
sns.histplot(restaurant_df['length'])

# !pip install konlpy jpype1

from wordcloud import WordCloud
from collections import Counter
from konlpy.tag import Okt
import matplotlib.pyplot as plt
import seaborn as sns
import os
import matplotlib.font_manager as fm

# ✅ 1. 리뷰는 이걸로!
text = ' '.join(review_df['review'].dropna())

# ✅ 2. 형태소 분석
okt = Okt()
words = [w for w in okt.nouns(text) if len(w) > 1]

freq = Counter(words)

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# ✅ 3. 워드클라우드

# 폰트 경로 직접 지정 (Added this line)
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'
if os.path.exists(font_path):
    fm.fontManager.addfont(font_path) # Ensure font is added if path is valid
    plt.rcParams['font.family'] = 'NanumGothic'
    plt.rcParams['axes.unicode_minus'] = False
else:
    print("❌ NanumGothic.ttf 파일을 찾을 수 없습니다. 설치 확인 필요")


wordcloud = WordCloud(
    font_path=font_path,
    background_color='white',
    width=1000, height=600,
    colormap='RdYlGn',
    max_words=100
).generate_from_frequencies(freq)

axes[0].imshow(wordcloud, interpolation='bilinear')
axes[0].axis('off')
axes[0].set_title('리뷰 키워드 워드클라우드', fontsize=15, fontweight='bold')
# axes[0].show()

# (선택) 상위 20개 막대그래프
top_20_words = freq.most_common(20)
words_, counts_ = zip(*top_20_words)

sns.barplot(x=counts_, y=words_, palette='Greens_r', ax=axes[1])
axes[1].set_title('리뷰 상위 20개 단어', fontsize=13, fontweight='bold')
axes[1].set_xlabel('등장 빈도')


plt.tight_layout()
plt.show()

plt.figure(figsize=(8,6))
sns.regplot(
    data=restaurant_df, x='length', y='rating',
    scatter_kws={'alpha':0.2, 'color':'#2E8B57', 's':40},
    line_kws={'color':'#E74C3C', 'linewidth':2},
)
plt.title('리뷰 길이에 따른 평점 경향', fontsize=15, fontweight='bold', pad=15)
plt.xlabel('리뷰 길이(문자 수)', fontsize=12)
plt.ylabel('평점', fontsize=12)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

corr = restaurant_df['length'].corr(restaurant_df['rating'])
print(f"📈 리뷰 길이와 평점의 상관계수: {corr:.3f}")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# 너무 긴 리뷰는 제외 (outlier 제거용)
filtered = restaurant_df[restaurant_df['length'] < 1000]

# 리뷰 길이를 20자 단위 구간으로 나누기
filtered['length_bin'] = (filtered['length'] // 20) * 20

# 각 구간별 평균 평점 계산
avg_rating = filtered.groupby('length_bin')['rating'].mean().reset_index()

plt.figure(figsize=(8,5))
sns.lineplot(data=avg_rating, x='length_bin', y='rating', marker='o', color='#2E8B57')

plt.title('리뷰 길이에 따른 평균 평점 변화', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('리뷰 길이 구간 (문자 수)')
plt.ylabel('평균 평점')
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

plt.rcParams['font.family'] = 'NanumGothic'
plt.rcParams['axes.unicode_minus'] = False

# 1️⃣ 회귀선 그래프 (전체 경향)
fig, axes = plt.subplots(1, 2, figsize=(14, 6))

sns.regplot(
    data=restaurant_df,
    x='length', y='rating',
    scatter_kws={'alpha':0.2, 'color':'#2E8B57', 's':40},
    line_kws={'color':'#E74C3C', 'linewidth':2},
    ax=axes[0]
)
axes[0].set_title('리뷰 길이에 따른 평점 경향', fontsize=14, fontweight='bold', pad=15)
axes[0].set_xlabel('리뷰 길이(문자 수)', fontsize=12)
axes[0].set_ylabel('평점', fontsize=12)
axes[0].grid(alpha=0.3)

# 2️⃣ 리뷰 길이 구간별 평균 그래프
restaurant_df['length_bin'] = (restaurant_df['length'] // 20) * 20
avg_by_length = restaurant_df.groupby('length_bin')['rating'].mean().reset_index()

axes[1].plot(avg_by_length['length_bin'], avg_by_length['rating'],
             marker='o', color='#2E8B57', linewidth=1.5)
axes[1].set_title('리뷰 길이에 따른 평균 평점 변화', fontsize=14, fontweight='bold', pad=15)
axes[1].set_xlabel('리뷰 길이 구간 (문자 수)', fontsize=12)
axes[1].set_ylabel('평균 평점', fontsize=12)
axes[1].grid(alpha=0.3)

# 3️⃣ 전체 스타일 정리
plt.suptitle('리뷰 길이에 따른 평점 변화 분석', fontsize=16, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,6))
sns.boxplot(
    x='site', y='rating', data=review_df,
    palette=['#81C784', '#1B5E20'],
    width=0.6, showmeans=True,
    meanprops={'marker':'o', 'markerfacecolor':'red', 'markeredgecolor':'black'},
    medianprops={'color':'yellow', 'linewidth':2}
)

summary = review_df.groupby('site')['rating'].agg(['mean','median','count']).round(2)
labels = [f"{site} ({int(row['count'])}개)" for site, row in summary.iterrows()]


for i, (site, row) in enumerate(summary.iterrows()):
    plt.text(i, row['mean'] + 0.05, f"평균 {row['mean']:.2f}", color='red', fontsize=11, fontweight='bold', ha='center')
    plt.text(i, row['median'] - 0.35, f"중앙값 {row['median']:.2f}", color='gold', fontsize=10, ha='center')

plt.title('플랫폼별 리뷰 평점 분포 비교', fontsize=15, fontweight='bold', pad=20)
plt.xlabel('리뷰 플랫폼', fontsize=12)
plt.ylabel('평점', fontsize=12)
plt.xticks(range(len(labels)), labels, fontsize=12)
plt.yticks([1,2,3,4,5], ['1점','2점','3점','4점','5점'])
plt.grid(axis='y', linestyle='--', alpha=0.3)

plt.tight_layout()
plt.show()

