# -*- coding: utf-8 -*-
"""캡스톤디자인_RAG+string_Matching_v11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ez74dHalSmqhGxpPhXZiapYpwIQ8Yh5Q

## 환경설정
"""

import logging
logging.basicConfig(level=logging.INFO)

from google.colab import drive
drive.mount('/content/drive')

# # !pip install gradio

# !pip uninstall -y langchain
# !pip install -U langchain

# !pip install -U langchain langchain-openai langchain-community

# !pip install -U langchain-text-splitters chromadb

# !pip install -U langchain-huggingface sentence-transformers

# !python3 --version

# !pip install konlpy

# !pip install kiwipiepy==0.22.1
# !pip install kiwipiepy_model==0.22.0

import os
import json
import pandas as pd
import numpy as np
from numpy.linalg import norm

from langchain_openai import OpenAIEmbeddings
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables import RunnableParallel, RunnablePassthrough
from langchain_community.vectorstores import Chroma
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.messages import AIMessage, HumanMessage
from langchain_huggingface import HuggingFaceEmbeddings

import re
from collections import Counter, defaultdict
from math import log
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

from IPython.display import display
import ipywidgets as widgets

from konlpy.tag import Okt

# from kiwipiepy import Kiwi

"""## 데이터 경로"""



VECTOR_DB_PATH = "/content/drive/MyDrive/CapStone/캡스톤/review_db_v13"
META_PATH = "/content/drive/MyDrive/CapStone/캡스톤/restaurant_metadata.json"

MENU_DATA_PATH = "/content/drive/MyDrive/CapStone/캡스톤/menu_data_final.csv"

"""## 공통함수"""

okt_tokenizer = Okt()
# kiwi = Kiwi()

def normalize_tokens(text, is_use_v=True):
    text = re.sub(r"[^가-힣a-zA-Z0-9\s]", " ", text)
    okt_pos_tags = okt_tokenizer.pos(text, stem=True)

    base_tokens = []
    for w, p in okt_pos_tags:
        if p in ["Noun", "Adjective", "Verb"]:
            base_tokens.append(w)

    if is_use_v:
        valid_prefixes = ("N", "V", "VA", "XR")  # 동사 포함
    else:
        valid_prefixes = ("N", "VA", "XR")       # 동사 제외

    result = set()
    for w, p in okt_pos_tags:
        # 품사 조건
        if p == "Noun":
            result.add(w)
        elif p == "Adjective":
            result.add(w)
        elif is_use_v and p == "Verb":  # 동사 포함 여부
            result.add(w)

    cleaned = set()
    for word in result:
        if word.endswith(("하다", "한")):
            base = re.sub(r"(하다|한)$", "", word)
            if len(base) >= 2:
                cleaned.add(base)
        cleaned.add(word)

    return list(cleaned)

def preprocess_query(text):
    stopwords = {"에서","으로","은","는","이","가","을","를","의","도","에",
                "로","과","와","고","들","좀","처럼","도","한"}
    tokens = normalize_tokens(text)
    return [t for t in tokens if t not in stopwords]

def normalize_attr_dict(attr_dict):
    normalized = {}
    for attr, keywords in attr_dict.items():
        expanded = set()
        for w in keywords:
            expanded.update(normalize_tokens(w))
        normalized[attr] = list(expanded)
    return normalized

def apply_time_filter(df, tokens):
    lunch_kw = ["점심", "런치", "브런치", "아점"]
    dinner_kw = ["저녁", "디너", "야식", "심야", "밤"]
    time_slot = None

    if any(t in tokens for t in lunch_kw):
        time_slot = "lunch"
    elif any(t in tokens for t in dinner_kw):
        time_slot = "dinner"

    if df is None:
        return None, time_slot

    if time_slot == "lunch":
        df_filtered = df[df.filter(regex="_lunch$").any(axis=1)]
        return df_filtered, time_slot

    elif time_slot == "dinner":
        df_filtered = df[df.filter(regex="_dinner$").any(axis=1)]
        return df_filtered, time_slot

    return df, time_slot

STATION_MAP = {
    "성수": ["성수", "성수역"],
    "서울숲": ["서울숲", "서울숲역"],
    "뚝섬": ["뚝섬", "뚝섬역"],
    "자양": ["자양", "자양동"],
    "건대입구": ["건대입구", "건대", "건대근처", "건대역", "건국대"],
    "어린이대공원": ["어린이대공원", "어린이대공원역", "어대공", "대공원"],
}

def extract_station_from_keywords(keywords, station_map=STATION_MAP):
    matched = set()
    keywords_str = " ".join(keywords)

    for std, syns in station_map.items():
        for syn in syns:
            if syn in keywords or syn in keywords_str:
                matched.add(std)
                break

    return list(matched)

def extract_query_intent(query):
    tokens = normalize_tokens(query)

    stations = extract_station_from_keywords(tokens)
    _, time_slot = apply_time_filter(None, tokens)

    return {
        "tokens": tokens,
        "stations": stations,
        "time_slot": time_slot,
    }

"""## 실시간 데이터"""



import requests
import json
from datetime import datetime, timedelta
import math
import xml.etree.ElementTree as ET
from math import radians, cos, sin, asin, sqrt

# SERVICE_KEY는 환경 변수에서 읽어옵니다
# export SERVICE_KEY="your-service-key" 또는 .env 파일 사용
SERVICE_KEY = os.environ.get("SERVICE_KEY")
if not SERVICE_KEY:
    raise ValueError("SERVICE_KEY 환경 변수가 설정되지 않았습니다.")
# REALTIME_CITY_DATA_URL = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/citydata/1/1000/'
REALTIME_CITY_DATA_URL = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/xml/citydata/1/1000/'
ATTR_LOCATION_KEY ={
    "성수" : "성수카페거리",
    "서울숲" : "서울숲공원",
    "뚝섬" : "뚝섬역",
    "건대입구" : "건대입구역",
    "어린이대공원" : "어린이대공원"
}

def get_station_to_location(station):
    return ATTR_LOCATION_KEY.get(station)

def get_city_datas():
    city_datas = {}
    stations = INTENT_STATE["stations"]
    for st in stations:
          loc = get_station_to_location(st)
          if not loc:
              continue

          url = REALTIME_CITY_DATA_URL + loc
          print(f"city data url : {url}")
          response = requests.get(url)

          if response.status_code != 200:
              continue

          city_datas[loc] = response.content.decode("utf-8")

    return city_datas

import pandas as pd
import xml.etree.ElementTree as ET

def xml_to_dataframe(xml_data, keyword):
    import xml.etree.ElementTree as ET
    if xml_data is None:
        return pd.DataFrame()

    if isinstance(xml_data, ET.Element):
        root = xml_data
    else:
        root = ET.fromstring(xml_data)

    rows = []
    for elem in root.findall(f".//{keyword}"):
        if len(list(elem)) == 0:
            continue

        row = {child.tag: child.text for child in elem}
        rows.append(row)

    df = pd.DataFrame(rows)

    df = df.dropna(how='all')
    return df.reset_index(drop=True)

"""### 인구 데이터"""

def get_pop_status_data(city_data):
    return xml_to_dataframe(city_data, "LIVE_PPLTN_STTS")

"""### 날씨 데이터"""

def get_weather_data(city_data):
    return xml_to_dataframe(city_data, "WEATHER_STTS")

"""### 주차 데이터"""

def haversine(target_lat, target_lon, actual_lat, actual_lon):
  r = 6371

  dlat = radians(actual_lat-target_lat)
  dlon = radians(actual_lon-target_lon)

  a = sin(dlat / 2)**2 + cos(radians(target_lat)) * cos(radians(actual_lat)) * sin(dlon / 2)**2
  c = 2 * asin(sqrt(a))

  return r * c * 1000

def get_parking_info(target_df, city_data):
    print(f"city_data : {city_data}")
    print(f"target_df : {target_df}")
    parking_df = xml_to_dataframe(city_data, "PRK_STTS")
    if parking_df.empty:
        print("주차장 데이터를 찾을 수 없습니다.")
        return pd.DataFrame()

    print(f"parking_df : {parking_df}")

    parking_df['LAT'] = parking_df['LAT'].astype(float)
    parking_df['LNG'] = parking_df['LNG'].astype(float)

    parking_df['distance'] = parking_df.apply(
        lambda row: haversine(target_df.iloc[0]['lon'], target_df.iloc[0]['lat'], row['LAT'], row['LNG']),
        axis=1
        )

    return parking_df.sort_values(by='distance', ascending=True).head(5)

"""지역명 기반 주차장 거리 계산"""
STATION_CENTER_COORDINATES = {
    "성수": (37.5446, 127.0551),
    "서울숲": (37.5434, 127.0447),
    "뚝섬": (37.5472, 127.0474),
    "건대입구": (37.5403, 127.0694),
    "어린이대공원": (37.5480, 127.0747)
}

def get_parking_info_by_location(location_name, city_data):

    if city_data is None:
        return pd.DataFrame()

    # PRK_STTS 파싱
    parking_df = xml_to_dataframe(city_data, "PRK_STTS")
    if parking_df.empty:
        return parking_df

    # 좌표 타입 변환
    parking_df["LAT"] = parking_df["LAT"].astype(float)
    parking_df["LNG"] = parking_df["LNG"].astype(float)

    # 지역 좌표 없는 경우 그대로 반환
    if location_name not in STATION_CENTER_COORDINATES:
        return parking_df

    # 중심 좌표
    center_lat, center_lon = STATION_CENTER_COORDINATES[location_name]

    # 거리 계산
    parking_df["distance"] = parking_df.apply(
        lambda row: haversine(
            center_lon, center_lat,
            row["LAT"], row["LNG"]
        ),
        axis=1
    )

    return parking_df.sort_values(by="distance")

"""### 테스트"""

# temp_data = get_city_datas()
# print(temp_data)
# temp_prk = get_prk_data(temp_data["성수카페거리"])
# print(temp_prk.head(3))



"""## RAG"""

# !apt-get install openjdk-11-jdk -y

EMBEDDING_MODEL = "BM-K/KoSimCSE-roberta-multitask"
LLM_MODEL = "gpt-4o-mini"

# API 키는 환경 변수에서 읽어옵니다
# export OPENAI_API_KEY="your-api-key" 또는 .env 파일 사용
if "OPENAI_API_KEY" not in os.environ:
    raise ValueError("OPENAI_API_KEY 환경 변수가 설정되지 않았습니다.")

def prepare_rag_env(
    vector_db_path: str,
    metadata_path: str,
    collection_name: str = "review_collection",
    embedding_model: str = "BM-K/KoSimCSE-roberta-multitask"
):

    vector_db = Chroma(
        collection_name=collection_name,
        embedding_function=OpenAIEmbeddings(model=embedding_model),
        persist_directory=vector_db_path
    )
    count = vector_db._collection.count()
    print(f"벡터DB 문서 로드 완료: {count}개")


    if not os.path.exists(metadata_path):
        raise FileNotFoundError(f"메타데이터 파일 없음: {metadata_path}")

    with open(metadata_path, "r", encoding="utf-8") as f:
      restaurant_metadata_list = json.load(f)

    restaurant_metadata_df = pd.DataFrame(restaurant_metadata_list)
    print(f"메타데이터 로드 완료: {len(restaurant_metadata_df)}개")

    vector_db_items = vector_db.get(include=["metadatas", "documents"])

    vector_db_metadata_df = pd.DataFrame(vector_db_items["metadatas"])
    vector_db_metadata_df["page_content"] = vector_db_items["documents"]

    print(f"DB에서 메타데이터 추출: {len(vector_db_metadata_df)}개")


    merged_restaurant_review_df = pd.merge(
        vector_db_metadata_df,
        restaurant_metadata_df,
        on="restaurant_id",
        how="left",
        suffixes=("_db", "_json")
    )


    print(f"병합 완료: {len(merged_restaurant_review_df)}개 매칭")
    display(merged_restaurant_review_df[["restaurant_id", "restaurant_name_db", "review_no"]].head(5))

    unmatched_restaurants = merged_restaurant_review_df[merged_restaurant_review_df["restaurant_name_json"].isna()]
    print(f"매칭 안 된 식당 수: {len(unmatched_restaurants)}")

    before_count = len(merged_restaurant_review_df)
    merged_restaurant_review_df = merged_restaurant_review_df[merged_restaurant_review_df["restaurant_name_json"].notna()].reset_index(drop=True)
    after_count = len(merged_restaurant_review_df)
    print(f" 매칭 안 된 식당 {before_count - after_count}개 삭제 완료")
    print(f"남은 데이터 수: {after_count}개")

    duplicate_columns_to_drop = ["restaurant_name_json", "category_1_json", "category_2_json", "station_json"]
    duplicate_columns_to_drop = [c for c in duplicate_columns_to_drop if c in merged_restaurant_review_df.columns]
    merged_restaurant_review_df = merged_restaurant_review_df.drop(columns = duplicate_columns_to_drop)
    print(merged_restaurant_review_df)

    print(f"최종 데이터셋 준비 완료: {len(merged_restaurant_review_df)}개")

    print("vector_db_metadata_df 컬럼 목록:\n", vector_db_metadata_df.columns.tolist())
    print("\n restaurant_metadata_df 컬럼 목록:\n", restaurant_metadata_df.columns.tolist())
    print("\n merged_restaurant_review_df 컬럼 목록:\n", merged_restaurant_review_df.columns.tolist())


    return vector_db, merged_restaurant_review_df

vector_db, merged_restaurant_review_df = prepare_rag_env(VECTOR_DB_PATH, RESTAURANT_METADATA_PATH)
embedding_model = HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL)

merged_restaurant_review_df.info()

merged_restaurant_review_df.head(3)

cols = ['restaurant_id'] + [c for c in merged_restaurant_review_df.columns if c != 'restaurant_id']
print(merged_restaurant_review_df[cols].sort_values(by='restaurant_id'))

os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["PATH"] += os.pathsep + os.path.join(os.environ["JAVA_HOME"], "bin")

"""### 1차 필터링"""

def apply_station_filter(df, keywords):
    if "station_db" not in df.columns:
        return df

    matched_station_names = INTENT_STATE["stations"]

    if not matched_station_names:
        return df

    station_filter_condition = pd.Series(False, index=df.index)
    for station_name in matched_station_names:
        station_filter_condition |= df["station_db"].astype(str).str.contains(station_name, na=False)

    return df[station_filter_condition]


def apply_category_filter(df, keywords):
    if "category_1_db" not in df.columns:
        return df

    keywords_str = " ".join(keywords)

    category_map = {
        "한식": ["한식", "백반", "국밥", "삼겹살", "목살", "칼국수", "보쌈", "한정식"],
        "일식": ["일식", "스시", "초밥", "라멘", "덮밥", "가츠동", "오마카세", "오니기리", "규동"],
        "중식": ["중식", "짜장", "짬뽕", "탕수육", "훠궈", "마라샹궈", "중화요리", "마라탕", "양꼬치"],
        "양식": ["양식", "파스타", "스테이크", "브런치"],
        "술집": ["술집", "바", "이자카야", "펍", "포차", "소주", "맥주", "포장마차", "안주"],
        "간식": ["간식", "카페", "까페", "베이커리", "빵집", "베이글", "브런치", "디저트"],
        "분식": ["분식", "떡볶이", "즉떡", "김밥", "라면"],
    }

    simple_categories = [
        "구내식당", "치킨", "패스트푸드", "퓨전요리", "도시락",
        "아시아음식", "샤브샤브", "뷔페", "샐러드", "패밀리레스토랑"
    ]

    category_keyword_used = (
        any(any(syn in keywords_str for syn in syns) for syns in category_map.values())
        or any(cat in keywords_str for cat in simple_categories)
    )

    if not category_keyword_used:
      return df

    category_filter_condition = pd.Series(True, index=df.index)
    is_category_matched = False


    for category_name, synonyms in category_map.items():
        if any(synonym in keywords_str for synonym in synonyms):
            category_filter_condition &= df["category_1_db"].str.contains(category_name, case=False, na=False)
            is_category_matched = True
            break

    if not is_category_matched:
        for category_name in simple_categories:
            if category_name in keywords_str:
                category_filter_condition &= df["category_1_db"].str.contains(category_name, case=False, na=False)
                is_category_matched = True
                break
    return df[category_filter_condition]



def apply_attribute_filter(df, keywords):
    attr_map = {
        "service_score": ["친절", "응대", "서비스", "빠른"],
        "ambience_score": ["분위기", "조용", "감성", "데이트", "아늑", "로맨틱", "기념일"],
        "price_score": ["저렴", "가성비", "합리적", "혜자"],
        "taste_score": ["맛있", "맛집", "훌륭"],
    }

    for col, syns in attr_map.items():
        if col in df.columns and any(s in keywords for s in syns):
            df = df[df[col] >= 0.5]

    return df


def build_filters(query, verbose=False):
    # keywords = normalize_tokens(query)
    keywords = INTENT_STATE["tokens"]
    total_review_count = len(merged_restaurant_review_df)
    filtered_reviews_df = merged_restaurant_review_df.copy()

    before_station_filter = len(filtered_reviews_df)
    filtered_reviews_df = apply_station_filter(filtered_reviews_df, keywords)
    if verbose:
        print(f"역 필터: {before_station_filter} → {len(filtered_reviews_df)}")

    before_time_filter = len(filtered_reviews_df)
    filtered_reviews_df, time_slot = apply_time_filter(filtered_reviews_df, keywords)
    if verbose:
        print(f"시간대 필터: {before_time_filter} → {len(filtered_reviews_df)}")

    before_category_filter = len(filtered_reviews_df)
    filtered_reviews_df = apply_category_filter(filtered_reviews_df, keywords)
    if verbose:
        print(f"카테고리 필터: {before_category_filter} → {len(filtered_reviews_df)}")

    before_attribute_filter = len(filtered_reviews_df)
    filtered_reviews_df = apply_attribute_filter(filtered_reviews_df, keywords)
    if verbose:
        print(f"속성 필터: {before_attribute_filter} → {len(filtered_reviews_df)}")

    if verbose:
        unique_restaurant_count = filtered_reviews_df['restaurant_name_db'].nunique()
        print(f"최종: {total_review_count} → {len(filtered_reviews_df)} (리뷰/식당 {unique_restaurant_count}개 남음)")

    return filtered_reviews_df



"""### 2차 임베딩

#### 기본 Retrieve
"""

def calc_review_similarity(vector_subset_dict, query_embedding):
    review_embedding_vectors = np.array(vector_subset_dict["embeddings"])
    similarity_scores = np.dot(review_embedding_vectors, query_embedding) / (
        norm(review_embedding_vectors, axis=1) * norm(query_embedding)
    )

    similarity_df = pd.DataFrame({
        "review_no": [metadata["review_no"] for metadata in vector_subset_dict["metadatas"]],
        "restaurant_id": [metadata["restaurant_id"] for metadata in vector_subset_dict["metadatas"]],
        "restaurant_name": [metadata["restaurant_name"] for metadata in vector_subset_dict["metadatas"]],
        "date": [metadata["date"] for metadata in vector_subset_dict["metadatas"]],
        "similarity": similarity_scores,
    })

    return similarity_df;

def retrieve_similar_reviews(query,
                             filtered_reviews_df,
                             lambda_weight=0.0001):

    query_embedding = embedding_model.embed_query(query)

    filtered_review_ids = filtered_reviews_df["review_no"].astype(int).tolist()

    vector_subset_dict = vector_db._collection.get(
        where={"review_no": {"$in": filtered_review_ids}},
        include=["embeddings", "metadatas"]
    )

    # print(f"벡터DB 임베딩 로드 개수: {len(vector_subset_dict['embeddings'])}")

    if len(vector_subset_dict["embeddings"]) == 0:
        return pd.DataFrame(), pd.DataFrame()

    similarity_result_df = calc_review_similarity(vector_subset_dict, query_embedding)
    # print(f"유사도 계산 결과 : {similarity_result_df.head(5)}")

    return similarity_result_df

"""#### Time Weight"""

def calc_timeWeighted_date(similarity_df, lambda_weight=0.0009):
    similarity_df["date"] = pd.to_datetime(similarity_df["date"], format="mixed")
    latest_review_date = similarity_df["date"].max()
    similarity_df["days_since"] = (latest_review_date - similarity_df["date"]).dt.days

    similarity_df["time_weight"] = np.exp(-lambda_weight * similarity_df["days_since"])
    similarity_df["weighted_similarity"] = similarity_df["similarity"] * similarity_df["time_weight"]

    return similarity_df

def time_weight_with_retrieve_similar_reviews(query,
                             filtered_reviews_df,
                             lambda_weight=0.0009):

    query_embedding = embedding_model.embed_query(query)

    filtered_review_ids = filtered_reviews_df["review_no"].astype(int).tolist()

    vector_subset_dict = vector_db._collection.get(
        where={"review_no": {"$in": filtered_review_ids}},
        include=["embeddings", "metadatas"]
    )

    print(f"벡터DB 임베딩 로드 개수: {len(vector_subset_dict['embeddings'])}")

    if len(vector_subset_dict["embeddings"]) == 0:
        return pd.DataFrame(), pd.DataFrame()

    similarity_result_df = calc_review_similarity(vector_subset_dict, query_embedding)
    # print(f"유사도 계산 결과 : {similarity_result_df.head(5)}")

    time_weighted_similarity_df = calc_timeWeighted_date(similarity_result_df, lambda_weight)
    # print(f"최신 리뷰 가중치 부여 결과 : {time_weighted_similarity_df.head(5)}")

    return time_weighted_similarity_df

"""
#### Result"""

def select_topk_groupby_restaurants(similarity_df, top_k=3, reviews_per_restaurant=10, sort_column="weighted_similarity"):
  top_restaurants_df = (
        similarity_df.sort_values(["restaurant_id", sort_column], ascending=[True, False])
        .groupby("restaurant_id")
        .head(reviews_per_restaurant)
        .groupby(["restaurant_id", "restaurant_name"], as_index=False)[sort_column]
        .mean()
        .sort_values(sort_column, ascending=False)
    )

  top_restaurants_df = top_restaurants_df.head(top_k)

  return top_restaurants_df

"""#### 필터링 + 임베딩"""

def rag_recommend_reviews(query):
    filtered_df = build_filters(query,True)

    raw_sim_df = retrieve_similar_reviews(query, filtered_df)
    retrieve_topk_df = select_topk_groupby_restaurants(raw_sim_df, sort_column="similarity")
    print(f"raw similarity top-k 결과 : {retrieve_topk_df.head(5)}")

    return retrieve_topk_df

def rag_recommend_reviews_with_time_weight(query):
    filtered_df = build_filters(query,True)

    time_weighted_df = time_weight_with_retrieve_similar_reviews(query, filtered_df)
    time_weight_topk_df = select_topk_groupby_restaurants(time_weighted_df, sort_column="weighted_similarity")
    print(f"time-weight top-k 결과 : {time_weight_topk_df.head(5)}")

    return time_weighted_df, time_weight_topk_df

def get_rest_metadata(restaurant_id):
    restaurant_row = merged_restaurant_review_df[merged_restaurant_review_df["restaurant_id"] == restaurant_id].head(1)
    if restaurant_row.empty:
        return {}
    return restaurant_row.iloc[0].to_dict()


def get_top_reviews_from_df(similarity_df, restaurant_id, top_k):

    return (
        similarity_df[similarity_df["restaurant_id"] == restaurant_id]
        .nlargest(top_k, "weighted_similarity")
    )


def get_reviews_from_vector_db(review_id_list):
    vector_db_result = vector_db._collection.get(
        where={"review_no": {"$in": review_id_list}},
        include=["documents", "metadatas"]
    )

    return list(zip(vector_db_result.get("documents", []),
                    vector_db_result.get("metadatas", [])))


def build_review_json(top_reviews_df, review_document_metadata_pairs):
    reviews_json_list = []
    for document_text, review_metadata in review_document_metadata_pairs:
        review_number = review_metadata.get("review_no")
        similarity_values = top_reviews_df[top_reviews_df["review_no"] == review_number]["weighted_similarity"].values
        weighted_similarity_score = float(similarity_values[0]) if len(similarity_values) else 0.0

        reviews_json_list.append({
            "review_no": review_number,
            "date": str(review_metadata.get("date")),
            "similarity": weighted_similarity_score,
            "text": document_text
        })

    print(f"reviews : {reviews_json_list}")
    return reviews_json_list


def retrieve_result_to_json(similarity_df, top_restaurants_df, top_k=3):
    restaurant_context_list = []

    for _, restaurant_row in top_restaurants_df.iterrows():
        restaurant_id = restaurant_row["restaurant_id"]
        restaurant_name = restaurant_row["restaurant_name"]

        restaurant_metadata = get_rest_metadata(restaurant_id)
        top_reviews_df = get_top_reviews_from_df(similarity_df, restaurant_id, top_k)

        review_document_metadata_pairs = get_reviews_from_vector_db(
            top_reviews_df["review_no"].astype(int).tolist()
        )
        reviews_json_list = build_review_json(top_reviews_df, review_document_metadata_pairs)

        restaurant_context_list.append({
            "restaurant_id": restaurant_id,
            "restaurant_name": restaurant_name,
            "meta": restaurant_metadata,
            "top_reviews": reviews_json_list
        })

    # print(f"retrieve_result_to_json : {top_restaurants_df.head(5)}")

    llm_context_data = {"restaurants": restaurant_context_list}
    print(f"restaurants : {llm_context_data}")


    return llm_context_data

"""### MMR"""

def select_reviews_mmr(
    query,
    # query_embedding,
    # review_embedding_vectors,
    # review_metadatas,
    lambda_mult=0.5,
    top_k=3,
    verbose=True
):

    filtered_reviews_df = build_filters(query)
    filtered_review_ids = filtered_reviews_df["review_no"].astype(int).tolist()
    query_embedding = embedding_model.embed_query(query)
    vector_subset_dict = vector_db._collection.get(
        where={"review_no": {"$in": filtered_review_ids}},
        include=["embeddings", "metadatas"]
    )
    review_embedding_vectors = np.array(vector_subset_dict["embeddings"])
    review_metadatas = vector_subset_dict["metadatas"]

    similarity_to_query = cosine_similarity([query_embedding], review_embedding_vectors)[0]
    similarity_between_reviews = cosine_similarity(review_embedding_vectors)

    #langchain의 MMR 수식을 직접 반영(쿼리와의 유사도는 높게, 이미 선택된 리뷰들과 유사도는 낮게 조정)
    selected_indices, remaining_indices = [], list(range(len(review_embedding_vectors)))
    while len(selected_indices) < top_k and remaining_indices:
        mmr_scores = [
            lambda_mult * similarity_to_query[idx]
            - (1 - lambda_mult) * max([similarity_between_reviews[idx][selected_idx] for selected_idx in selected_indices] or [0])
            for idx in remaining_indices
        ]
        best_mmr_idx = remaining_indices[np.argmax(mmr_scores)]
        selected_indices.append(best_mmr_idx)
        remaining_indices.remove(best_mmr_idx)

    selected_review_metadatas = [review_metadatas[idx] for idx in selected_indices]
    selected_similarity_scores = similarity_to_query[selected_indices]

    mmr_result_df = pd.DataFrame({
        "review_no": [metadata.get("review_no") for metadata in selected_review_metadatas],
        "restaurant_id": [metadata.get("restaurant_id") for metadata in selected_review_metadatas],
        "restaurant_name": [metadata.get("restaurant_name") for metadata in selected_review_metadatas],
        "date": [metadata.get("date") for metadata in selected_review_metadatas],
        "similarity": selected_similarity_scores,
    })

    if verbose:
        print(f"\n MMR 기반 리뷰 Top-{top_k} 선정 완료:")
        for _, restaurant_row in mmr_result_df.iterrows():
            print(f"- {restaurant_row['restaurant_name']} ({restaurant_row['similarity']:.3f})")

    return mmr_result_df

"""## 메뉴기반 추출

### 메뉴 + 역 정보 병합
"""

# ##각 메뉴 타이틀, tokenize

# df = pd.read_csv('/content/drive/MyDrive/Ehwa/캡스톤/menu_with_store.csv')
# menu_store_df  = df.copy()
# menu_store_df["title_tokens"] = menu_store_df["menu_title"].astype(str).apply(normalize_tokens)
# menu_store_df.head()

# menu_store_token = pd.read_csv('/content/drive/MyDrive/Ehwa/캡스톤/menu_with_token.csv')
# menu_store_token.head()
# menu_store_token.info()

# menu_store_token.head(5)

# station_map = merged_df[['restaurant_id', 'station_db']].drop_duplicates(subset=['restaurant_id'])
# station_map.head(10)

# # 각 메뉴타이틀 장소 삽입
# menu_store_token = menu_store_token.merge(
#     station_map[['restaurant_id','station_db']],
#     on='restaurant_id',
#     how='left'
# )
# menu_store_token = menu_store_token.rename(columns={'station_db': 'station'})
# menu_store_token.head(10)
# print(menu_store_token.sort_values(by='restaurant_id'))

# missing_ids = menu_store_token.loc[
#     menu_store_token['station'].isna(),
#     'restaurant_id'
# ].unique()

# print("station NaN restaurant_id 개수:", len(missing_ids))
# print("일부 확인:", missing_ids[:10])

# nan_ratio = menu_store_token['station'].isna().mean()
# print(f"station NaN 비율: {nan_ratio:.2%}")

# menu_store_token[menu_store_token['station'].isna()].head()

# menu_store_token.to_csv('/content/drive/MyDrive/Ehwa/캡스톤/menu_data_final.csv', index=False, encoding='utf-8-sig')



"""###string matching"""

menu_raw_df = pd.read_csv(MENU_DATA_PATH)
menu_store_df  = menu_raw_df.copy()


TEXT_COLS = ["menu_title"]

ATTRIBUTE_COLS = ["spicy", "vegan", "meat", "seafood",
                  "diet", "dessert", "healthy",
                  "bakery", "alcohol_pair", "beverage_alcohol",
                  "soup", "cold", "hot"]

ATTR_TRANSLATIONS = {
    "spicy": ["매운", "얼큰한", "칼칼한", "자극적인", "매콤한"],
    "vegan": ["비건", "채식", "채소만", "고기없는"],
    "meat": ["고기", "삼겹살", "소고기", "돼지고기", "닭고기", "육류"],
    "seafood": ["해산물", "생선", "새우", "조개", "오징어", "회"],
    "diet": ["다이어트", "저칼로리", "가볍게", "살안찌는"],
    "dessert": ["디저트", "케이크", "빙수", "아이스크림", "달달한"],
    "healthy": ["건강식", "영양식", "담백한", "저염식"],
    "bakery": ["베이커리", "빵", "크로와상", "바게트"],
    "alcohol_pair": ["안주", "술안주", "맥주안주", "소주안주"],
    "beverage_alcohol": ["음료", "술", "맥주", "소주", "칵테일", "커피"],
    "soup": ["국물", "찌개", "탕", "국"],
    "cold": ["차가운", "시원한", "냉면", "냉국수"],
    "hot": ["따뜻한", "뜨거운", "데운", "온"]
}


TIME_ATTR_WEIGHTS = {
  "lunch": {
        # 점심 주력: 든든한 식사, 건강
        "rice": 2.5,
        "noodle": 2.5,
        "healthy": 2.0,
        "vegan": 2.0,
        "diet": 2.0,
        "meat": 1.5,      # 점심 고기도 괜찮음

        # 점심 비선호 (패널티)
        "alcohol_pair": 0.5,
        "beverage_alcohol": 0.5,
        "spicy": 1.0,     # 너무 매운건 점심에 부담일 수 있음 (중립)
    },

    "dinner": {
        # 저녁 주력: 술, 회식, 거한 요리
        "alcohol_pair": 3.0,      # 술 안주 (강력)
        "beverage_alcohol": 3.0,  # 주류 (강력)
        "meat": 2.5,              # 고기
        "seafood": 2.5,           # 해산물
        "spicy": 2.5,             # 매운맛
        "hot": 2.0,               # 뜨거운 요리
        "soup": 2.0,              # 국물

        # 저녁 비선호
        "bakery": 0.6,            # 빵은 식사로 부족
        "dessert": 0.6,
        "diet": 0.8,              # 저녁 회식때 다이어트는 잠시...
    },
}


ATTR_TRANSLATIONS_NORM = normalize_attr_dict(ATTR_TRANSLATIONS)


def detect_attributes(attr_dict, threshold =0):
    attr_scores = {attr: 0 for attr in attr_dict}

    for attr, keywords in attr_dict.items():
        for word in INTENT_STATE["tokens"]:
            if word in keywords:
                attr_scores[attr] += 1

    detected = [attr for attr, score in attr_scores.items() if score > threshold]
    detected = sorted(detected, key=lambda x: attr_scores[x], reverse=True)

    return detected if detected else None

def preprocess_dataframe(df, query):
    if "뷔페" not in query:
      df = df[~(
          (df["category_1"].str.contains("뷔페", na=False)) |
          (df["menu_title"].str.contains("뷔페", na=False))
      )]
    if "세트" not in query:
      df = df[~(
          (df["menu_title"].str.contains("정식", na=False))|
          (df["menu_title"].str.contains("세트", na=False))
      )]
    return df



def score_menus(df, rating_weight=0.2):
    detected_attrs = detect_attributes(ATTR_TRANSLATIONS_NORM,threshold=0)
    print("감지된 속성:", detected_attrs)
    print("감지된 시간대:", INTENT_STATE["time_slot"])
    df = df.drop_duplicates(subset=["restaurant_id"]).copy()

    def calc_simple_score(row):
      if not detected_attrs: return 0.0
      total = sum(row.get(attr, 0) * 1.0 for attr in detected_attrs)
      return total / len(detected_attrs)

    def calc_weighted_score(row):
      if not detected_attrs: return 0.0
      total = 0.0
      for attr in detected_attrs:
          base_val = row.get(attr, 0)
          w = 1.0
          if INTENT_STATE.get("time_slot") in TIME_ATTR_WEIGHTS:
              if attr in TIME_ATTR_WEIGHTS[INTENT_STATE["time_slot"]]:
                  w = TIME_ATTR_WEIGHTS[INTENT_STATE["time_slot"]][attr]
      total += base_val * w
      return total / len(detected_attrs)


    if "rating_bayes" not in df.columns:
        df["rating_bayes"] = 2.0

    df["temp_simple"] = df.apply(calc_simple_score, axis=1)
    df["temp_time_slot"] = df.apply(calc_weighted_score, axis=1)
    df["match_score"] = df["temp_time_slot"]

    df["rating_bayes"] = pd.to_numeric(df["rating_bayes"], errors="coerce").fillna(0)
    df["match_score"] = pd.to_numeric(df["match_score"], errors="coerce").fillna(0)




    # print(f"베이지안 30% {}")
    df["베이지안"] = rating_weight * df["rating_bayes"]

    df["속성가중치점수"] = 0.8 * df["temp_simple"]
    df["시간대가중치점수"] = 0.8 * df["match_score"]

    df["최종 속성가중치점수"] = 0.8 * df["temp_simple"] + rating_weight * df["rating_bayes"]
    df["score_attrs"] = 0.8 * df["match_score"] + rating_weight * df["rating_bayes"]


    df["rank_simple"] = df["최종 속성가중치점수"].rank(ascending=False, method='min').astype(int)
    df["rank_final"] = df["score_attrs"].rank(ascending=False, method='min').astype(int)
    def make_rank_change_str(row):
        old_rank = row["rank_simple"]
        new_rank = row["rank_final"]
        diff = old_rank - new_rank
        if diff > 0:
            return f"{old_rank}위 ➡ {new_rank}위 (🔺{diff})"
        elif diff < 0:
            return f"{old_rank}위 ➡ {new_rank}위 (🔻{abs(diff)})"
        else:
            return f"{new_rank}위 (-)"

    df["rank_change"] = df.apply(make_rank_change_str, axis=1)

    print("[비교] 속성 가중치 로직 vs 속성+시간 가중치 로직 순위 변동 확인")
    cols = ["name","menu_title", "속성가중치점수", "시간대가중치점수", "최종 속성가중치점수", "score_attrs", "rank_change","베이지안"]

    print("\n--- 속성 가중치 점수(w=1) 기준 Top 3 ---")
    print(df.sort_values("최종 속성가중치점수", ascending=False)[cols].head(5))

    print("\n--- 속성 + 시간 가중치 점수 기준 Top 3 ---")
    print(df.sort_values("score_attrs", ascending=False)[cols].head(5))

    display_df = df.sort_values("score_attrs", ascending=False)[cols].head(5)
    display(display_df)
    # print(df["match_score"].dtype, df["rating_bayes"].dtype)
    # print(df[["match_score", "rating_bayes"]].head())


    temp_df = df.copy()
    merged_meta = merged_df.copy()
    exclude_cols = ["menu_dict"]
    merge_target = merged_meta.drop(columns=exclude_cols)


    result = temp_df.merge(
        merge_target,
        on="restaurant_id",
        how="left"
    )
    result = result.sort_values(
        by=["score_attrs", "taste_score"],
        ascending=[False, False])

    result = result.drop_duplicates(
        subset=["restaurant_id", "menu_title"]
    ).reset_index(drop=True)

    # print("score_menus")
    display(result.head(2))
    return result.head(2)

import unicodedata
import ast

def score_menu_title(df, rating_weight=0.2):
    df = df.copy()

    def convert_to_list(x):
        if isinstance(x, str):
            try:
                return ast.literal_eval(x)
            except:
                return []
        return x

    df["title_tokens"] = df["title_tokens"].apply(convert_to_list)

    def clean_text(text):
        if not isinstance(text, str):
            return str(text)
        return unicodedata.normalize('NFC', text).replace(" ", "")

    menu_keywords = []
    normalized_search_tokens = [clean_text(t) for t in INTENT_STATE["tokens"]]

    for token in normalized_search_tokens:
        if df["title_tokens"].apply(lambda toks: token in clean_text("".join(toks) if isinstance(toks, list) else str(toks))).any():
            menu_keywords.append(token)

    menu_keywords = list(set(menu_keywords))
    print(f"검색 키워드: {menu_keywords}")

    if not menu_keywords:
        df["score_title"] = 0
        return df


    def calculate_score(title_tokens):
        if not isinstance(title_tokens, list) or not title_tokens:
            return 0.0

        score = 0.0

        clean_tokens = [clean_text(t) for t in title_tokens]
        full_name = "".join(clean_tokens)

        for kw in menu_keywords:
            kw_clean = kw

            if kw_clean in clean_tokens:
                score += 1.0

            elif kw_clean in full_name:
                score += 0.7

        return score

    df["match_score"] = df["title_tokens"].apply(calculate_score)

    if menu_keywords:
        df["score_title"] = df["match_score"] / len(menu_keywords)
    else:
        df["score_title"] = 0


    df["베이지안"] = rating_weight * df["rating_bayes"]
    # df["score_title"] = df["title_tokens"].apply(score)


    df["키워드매칭점수"] = 0.8 * df["score_title"]
    df["score_title"] = 0.8 * df["score_title"] + rating_weight * df["rating_bayes"]

    temp_cols = ["name", "menu_title","match_score","score_title","title_tokens","베이지안"]

    print("\n--- 메뉴스트링매칭 Top 3 ---")
    display(df.sort_values("score_title", ascending=False)[temp_cols].head(10))



    temp_df = df.copy()
    merged_meta = merged_df.copy()
    exclude_cols = ["menu_dict"]
    merge_target = merged_meta.drop(columns=exclude_cols)


    result = temp_df.merge(
        merge_target,
        on="restaurant_id",
        how="left"
    )

    result = result.sort_values(
        by=["score_title", "taste_score"],
        ascending=[False, False]
    )

    result = result.drop_duplicates(
        subset=["restaurant_id", "menu_title"]
    ).reset_index(drop=True)

    # print("score_menu_title")
    display(result)
    return result.head(2)

def recommend_menu(query, w_attr=0.7, w_title=0.3):
    tokens = preprocess_query(query)

    base_df = menu_store_df.copy()

    if INTENT_STATE["stations"]:
        st = INTENT_STATE["stations"]
        print(f"menu data station filter : {st}")
        print(f"menu data station filter 적용 전 : {len(base_df)} rows")
        display(base_df.head(5))
        base_df = base_df[base_df["station"].astype(str).isin(st)]
        print(f"menu data station filter 적용 후: {st} → {len(base_df)} rows")
        display(base_df.head(5))

    df_attrs = score_menus(
        preprocess_dataframe(base_df.copy(), query),
    )
    # print(f"menus : {len(df_attrs)}")
    # display(f"menus : {df_attrs.head(2)}")
    # print(df_attrs.columns)

    df_title = score_menu_title(base_df.copy())
    # print(f"menus2 : {len(df_title)}")
    # display(f"menus2 : {df_title.head(2)}")
    # print(df_title.columns)

    return df_attrs,df_title

# def built_context(retrieve_df,
#     topk_df,
#     # mmr_df,
#     select_df_menu,
#     select_df_menu_title,):

#   context = {
#     "retrieve_review": retrieve_result_to_json(retrieve_df, topk_df),
#     # "mmr": convert_df_to_json(
#     #     mmr_df,
#     #     ["review_no","restaurant_id","restaurant_name","date","similarity"],
#     #     max_rows=10
#     # ),
#     "menus": convert_df_to_json(
#         select_df_menu,
#         ["id","name" ,"menu_title"],
#         max_rows=5
#     ),
#     "menus2": convert_df_to_json(
#         select_df_menu_title  ,
#         ["id","name" ,"menu_title"],
#         max_rows=5
#     )
#     }

#     print(f"context : {context}")

#     return context

"""## Chain

### 프롬프트
"""

conversation_history = []
last_llm_context = None

SYSTEM_PROMPT = """
당신은 성수, 서울숲, 자양, 건대입구 지역의 맛집을 추천하는 챗봇입니다.
답변하기 전에 아래 조건들을 단계적으로 분석하고 최적의 결론을 도출하세요.
그러나 분석 과정은 사용자에게 공개하지 말고,
최종 결론만 명확하고 간결하게 제시하세요.

**반드시 제공된 JSON 데이터(context) 와 추가로 제공될 수 있는 (parking_info) 안의 정보만 사용하여 답변하세요.**
JSON에 없는 식당 / 메뉴 / 평가 / 특징을 생성하거나 추측하지 마세요.
정보가 부족할 경우 다음 문장을 그대로 출력합니다:
"관련 정보가 없습니다"

## context:
{context}

## 사용자 질문:
{question}


# ★ 내부 추론 프로세스 (최종 답변에 포함 금지)

답변을 생성하기 전에, 반드시 다음 단계를 내부적으로 수행하십시오:

1.  **질문 유형 분류 (Classification):** {question}과 chat_history를 검토하여 이 질문이 "처음 질문"인지 "후속 질문"인지 판별합니다.
  1.1. chat_history가 비어있으면 → “처음 질문”
  1.2. chat_history가 비어있지 않으면 → “후속 질문”

2.  **데이터 사용 계획 (Planning):**
    * "처음 질문": context의 JSON 데이터를 사용하여 **추천 로직**을 실행하고, 아래 지정된 **텍스트 출력 형식**에 따라 추천 목록을 생성합니다.
    * "후속 질문": context의 JSON 데이터 내에서 {question}에 직접적으로 관련된 정보만 검색하여 **자연스러운 대화** 형식으로 응답할 계획을 세웁니다.

3. "처음 질문" 규칙
  3.1. 추천 로직:
  - 리뷰 기반: similarity를 이용한 결과 기반
  - 메뉴 기반: menus, menus2 기반
  - 가격, 분위기, 거리 등 JSON에 없는 정보 언급 금지
  - "서로다른 식당" 모두 추천 (없으면 "없음" 명시)

  3.2.텍스트 출력 형식

  리뷰기반과 메뉴기반 추천 식당 1개 당 다음 항목을 **순서대로** 나열하여 추천 목록을 구성하며 ****3개 이상의 최대한 많은****식당을 추천합니다.(답변에 직접적으로 이 멘트를 하는건 금지)

  1) 추천 식당명: (식당 이름)
     - 추천 메뉴: (context에 있는 메뉴명들을 쉼표로 나열: 메뉴1, 메뉴2, 메뉴3...)
     - 메뉴 특징: (매운/국물/바삭함/가성비/분위기 등, menus/menus2 속성 필드가 있을 경우에만 요약)
     - Best review: "(review 항목이 있을 경우 similarity가 가장 높은 "text" 값을 원문 그대로“<...>” 형식으로 언급)
     - 가는 방법: (distance_m, distance_from_station 등 거리/시간 정보 활용하여 자연스럽게 서술)
     - 추천 이유: context에 있는 추천 식당의 모든 리뷰를 참고하여 추천 식당의 핵심 특징, 주 메뉴의 속성, 언급된 분위기를 기반으로 자연스럽게 작성
     - URL : kakao_url에 있는 링크를 클릭하면 연결할 수 있도록 함


  위 항목들 중, context에 해당 필드가 없으면 그 항목은 생략 합니다.


4. "후속 질문" 규칙

4.1. 답변 규칙
  후속 질문은 ** 기존에 제공된 {context}와 추가로 제공될 수 있는 parking_info와 chat_history 기반 대화**를 목표로 하며, 다음을 절대 금지합니다:
  - 새로운 식당, 메뉴, 리뷰 추가 생성
  - 추천 로직 / 필터링 / retrieval 재수행 (새로운 추천 목록 생성 금지)
  - ***처음 질문의 텍스트 출력 형식을 따르지 말것***

4.2. 텍스트 구성 가이드

  - 사용자가 "주차", "주차장", "차 가져가도 돼?" 등 주차 관련 질문을 하면:
    * FEWSHOT_PARKING 내용을 참고하여 친절하게 답변합니다
    * 여러 주차장이 있을 경우, 거리(distance)가 가깝거나 남은 자리(CPCTY - CUR_PRK_CNT)가 더 많은 곳을 중심으로 비교 설명
  - 날씨/인구 혼잡도 관련 후속 질문이면:
    * weather_info, pop_status_info 안에 있는 값만 사용해서 한두 문장으로만 현재 상황을 설명한 후, 후속질문에 맞는 답변으로 활용함
  - 이전 대화 목록인 chat_history를 종합하여 질문 내용을 추론

  - {context}에 없는 정보는 절대 추측/생성하지 말고,
    정말로 관련 필드가 없으면 "관련 정보가 없습니다"라고만 답변합니다.


5. 최종 검증 (Self-Verification)

5.1.  **출력 형식 강제:** "처음 질문"에 대한 답변은 **위에서 정의된 텍스트 추천 목록 형식**으로만 구성되어야 하며, **추천 식당명**부터 시작해야 합니다.
5.2. 부정적인 리뷰가 있는 경우에는 추천 식당에서 제외

----------------------------------------------------

# ★ 중요 요약 (Agent Goal)

- 처음 질문 → **추천 식당 목록** + 리뷰/메뉴/역/거리 등을 최대한 활용해서 최대한 많은 식당을 제안 (단, 모두 context 안에 있는 값만 사용)
- 후속 질문 → chat_history와 context를 기반으로 맥락 있게 보완 설명, **새로운 후보 생성 금지**, 주차/날씨/혼잡도는 parking_info, weather_info, pop_status_info 필드만 활용
"""

FEWSHOT_PARKING = """
[Few-shot Example #1 — "Parking info" 제공되는 경우 경우]

System Context:
{{
  "parking_info": [
   {{
      "PRK_NM": "성수1공영주차장",
      "CPCTY": "98",
      "CUR_PRK_CNT": "33",
      "distance": 121.4,
      "PAY_YN": "Y",
      "RATES": "1000",
      "TIME_RATES": "60",
      "ADD_RATES": "500",
      "ADD_TIME_RATES": "30"
      }}
  ],
  "retrieve_review": {{
    "restaurants": [{{ "restaurant_name": "성수우동" }}]
  }}
}}

Human:
성수우동 근처에 주차할 곳 있어?

Assistant:
네! 성수우동과 가장 가까운 주차장은 **성수1공영주차장**입니다.
- 총 98대 중 33대 주차 → 65대 남음
- 거리: 약 121m
- 요금: 1시간 1,000원, 30분 500원 추가
실시간 정보 제공됩니다.


[Few-shot Example #2 — "parking info" 없는 경우]

System Context:
{{
  "parking_info": []
}}

Human:
성수우동 근처 주차장 알려줘

Assistant:
현재 제공된 XML 데이터에는 주차장 정보가 없습니다.
필요 시 주차 앱에서 실시간 확인을 추천드립니다.


[Few-shot Example #3 — 여러개 주차장 정보가 있는 경우]

System Context:
{{
  "parking_info": [
    {{ "PRK_NM": "성수1공영주차장", "CPCTY": "98", "CUR_PRK_CNT": "90", "distance": 200 }},
    {{ "PRK_NM": "성수2공영주차장", "CPCTY": "120", "CUR_PRK_CNT": "50", "distance": 350 }}
  ]
}}

Human:
성수 근처 주차 어디가 좋아?

Assistant:
가장 가까운 곳은 **성수1공영주차장(200m)** 이지만 남은 공간은 8대입니다.
여유 있는 주차를 원한다면 **성수2공영주차장(남은 자리 70대)** 을 추천드립니다.
"""


HUMAN_PROMPT = "{question}"

"""### pipe line"""

prompt = ChatPromptTemplate.from_messages([
    ("system", SYSTEM_PROMPT),
    ("system", FEWSHOT_PARKING),
    MessagesPlaceholder("chat_history"),
    ("system", "다음 JSON을 참고하세요:\n{context}"),
    ("human", HUMAN_PROMPT)
])


llm = ChatOpenAI(model="gpt-4o-mini")

rag_chain = prompt | llm


def fix_timestamps(obj):
    if isinstance(obj, pd.Timestamp):
        return obj.isoformat()

    if isinstance(obj, dict):
        return {k: fix_timestamps(v) for k, v in obj.items()}

    if isinstance(obj, (list, tuple)):
        container = type(obj)
        return container(fix_timestamps(v) for v in obj)
    return obj


def convert_df_to_json(df, columns, max_rows=20):
    df = df[columns].head(max_rows)
    return df.to_dict(orient="records")

def format_docs_for_prompt(docs):
    formatted = []
    for d in docs:
        if isinstance(d.page_content, dict):
            formatted.append(d.page_content)
        else:
            formatted.append({"content": d.page_content})
    return json.dumps(formatted, ensure_ascii=False, indent=2)

def invoke_rag_chain(
    user_query,
    llm_context,
    conversation_history
):

    llm_response = rag_chain.invoke({
        "question": user_query,
        "context": llm_context,
         "chat_history": conversation_history
    })


    conversation_history.append(HumanMessage(content=user_query))
    conversation_history.append(AIMessage(content=llm_response.content))


    return llm_response.content, conversation_history

"""## 질문주제구분"""

def is_parking_query(text):
    parking_keywords = [
        "주차", "주차장", "발렛", "주차비", "공영주차장",
        "차 대", "파킹", "주차 가능", "만차", "정산"
    ]
    return any(kw in text for kw in parking_keywords)

def is_weather_query(text):
    weather_keywords = [
        "날씨", "기온", "온도", "추워", "더워", "더운", "추운", "시원한",
        "따뜻한", "비와", "눈와", "맑아", "흐려", "강수", "바람", "습도",
        "미세먼지", "먼지", "바깥", "실내", "밖에", "야외", "루프탑", "테라스"
    ]
    return any(kw in text for kw in weather_keywords)

INTENT_STATE = {
  "tokens": [],
  "stations": [],
  "time_slot": None
}

"""## 챗봇

### 자율형 챗봇
"""

def get_matched_restaurants(llm_context, restaurant_name_tokens):
    all_restaurants_list = []
    for restaurant_data in llm_context.get("retrieve_review", {}).get("restaurants", []):
        all_restaurants_list.append({
            "restaurant_id": restaurant_data.get("restaurant_id"),
            "restaurant_name": restaurant_data.get("restaurant_name"),
            "meta": restaurant_data.get("meta", {})
        })

    for menu_data in llm_context.get("menus", []):
        all_restaurants_list.append({
            "restaurant_id": menu_data.get("restaurant_id"),
            "restaurant_name": menu_data.get("restaurant_name_db"),
            "meta": restaurant_data.get("meta", {})
        })

    for menu_title_data in llm_context.get("menus2", []):
        all_restaurants_list.append({
            "restaurant_id": menu_title_data.get("restaurant_id"),
            "restaurant_name": menu_title_data.get("restaurant_name_db"),
            "meta": restaurant_data.get("meta", {})
        })

    unique_restaurants_dict = {
        restaurant_info["restaurant_id"]: restaurant_info
        for restaurant_info in all_restaurants_list if restaurant_info.get("restaurant_id") is not None
    }

    matched_restaurants_list = [
        restaurant_info for restaurant_info in list(unique_restaurants_dict.values())
        if restaurant_info.get("restaurant_name") and any(token in restaurant_info["restaurant_name"] for token in restaurant_name_tokens)
    ]

    return matched_restaurants_list

def standard_run_query(query, history):
  try:
    import gradio as gr
    global conversation_history, last_llm_context, INTENT_STATE, city_datas
    llm_context = {}
    print(f"query: {query}")

    intent = extract_query_intent(query)

    if intent["tokens"]:
        INTENT_STATE["tokens"] = intent["tokens"]
    if intent["stations"]:
        INTENT_STATE["stations"] = intent["stations"]
    if intent["time_slot"]:
        INTENT_STATE["time_slot"] = intent["time_slot"]

    print("INTENT_STATE:", INTENT_STATE)



    pop_status_df = pd.DataFrame()
    weather_df = pd.DataFrame()
    rag_retrieve_df = pd.DataFrame()
    rag_time_weight_df = pd.DataFrame()
    rag_mmr_df = pd.DataFrame()
    select_df_menu = pd.DataFrame()
    select_df_menu_title = pd.DataFrame()

    is_first_question = (last_llm_context is None and len(conversation_history) == 0)
    print(f"is_first_question = {is_first_question}")

    if is_first_question:
        city_datas = get_city_datas()
        print(city_datas)
        station = INTENT_STATE["stations"][0] if INTENT_STATE["stations"] else None
        if( station is not None ):
          lo = get_station_to_location(station)
          pop_status_df = get_pop_status_data(city_datas.get(lo))
          display(pop_status_df)
          weather_df = get_weather_data(city_datas.get(lo))
          display(weather_df)

        rag_retrieve_df = rag_recommend_reviews(query)
        temp_rag_retrieve_df, rag_time_weight_df = rag_recommend_reviews_with_time_weight(query)
        rag_mmr_df = select_reviews_mmr(query)
        select_df_menu, select_df_menu_title = recommend_menu(query)

        llm_context = {
            "pop_status_info": pop_status_df.to_dict(orient="records"),
            "weather_info": weather_df.to_dict(orient="records"),
            "retrieve_review": retrieve_result_to_json(temp_rag_retrieve_df, rag_time_weight_df),
            "menus": select_df_menu.to_dict(orient="records"),
            "menus2": select_df_menu_title.to_dict(orient="records")
        }

        print(f"llm_context : {llm_context}")
        llm_answer, conversation_history = invoke_rag_chain(query, llm_context, conversation_history)
        last_llm_context = llm_context
        history.append((query, llm_answer))
        print(f"llm_answer : {llm_answer}")
        return history, "", pop_status_df, weather_df, rag_retrieve_df, rag_time_weight_df, rag_mmr_df, select_df_menu, select_df_menu_title

    else:
        if is_parking_query(query):
          restaurant_name_tokens = INTENT_STATE["tokens"]
          print("restaurant_name_tokens:", restaurant_name_tokens)
          matched_restaurants = get_matched_restaurants(last_llm_context, restaurant_name_tokens)
          print("matched_restaurants:", matched_restaurants)

          if matched_restaurants:
              rid = matched_restaurants[0]["restaurant_id"]
              print("rid:", rid)
              lo = get_station_to_location(INTENT_STATE["stations"][0])
              print("lo:", lo)

              # temp_df = pd.DataFrame([matched_restaurants[0]["meta"]])
              # print("temp_df:", temp_df)
              print(f"is_parking_query city_datas : {city_datas}")
              parking_info = get_parking_info(
                  pd.DataFrame([matched_restaurants[0]["meta"]]), city_datas.get(lo)
              ).head(3)
              print("Parking Info:", parking_info)
          else:
              if INTENT_STATE["stations"]:
                        lo = get_station_to_location(INTENT_STATE["stations"][0])
                        parking_info = get_parking_info_by_location(
                            lo,
                            city_datas.get(lo)
                        ).head(3)
              else:
                  parking_info = pd.DataFrame()

          last_llm_context['parking_Info'] = parking_info.to_dict(orient="records")
          display(parking_info)

    print("last_llm_context:", last_llm_context)
    llm_answer, conversation_history = invoke_rag_chain(query, last_llm_context, conversation_history)
    history.append((query, llm_answer))
    print(f"llm_answer : {llm_answer}")
    return history, "", gr.update(), gr.update(), gr.update(), gr.update(), gr.update(), gr.update(), gr.update()

  except Exception as e:
    print(f"Error: {type(e).__name__}: {e}")
    return history, "", gr.update(), gr.update(), gr.update(), gr.update(), gr.update(), gr.update(), gr.update()


def reset_conversation():
    global conversation_history, last_llm_context, INTENT_STATE
    print("DEBUG: RESET CALLED")
    conversation_history = []
    last_llm_context = None
    INTENT_STATE = {
        "tokens": [],
        "stations": [],
        "time_slot": None
    }
    city_datas = {}
    return [], ""

"""### 가이드형 챗봇"""

# def step1_selected(evt: gr.SelectData):
#     # evt.value는 선택된 텍스트입니다.
#     return gr.update(visible=True), f"선택된 위치: {evt.value}"

# def step2_selected(evt: gr.SelectData):
#     return gr.update(visible=True), f"선택된 목적: {evt.value}"

# def step3_selected(evt: gr.SelectData):
#     return gr.update(visible=True), f"선택된 메뉴: {evt.value}"

# def reset_all():
#     return (
#         gr.update(value=None),
#         gr.update(value=None, visible=False),
#         gr.update(value=None, visible=False),
#         gr.update(visible=False),
#         []
#     )

def custom_run_query(query, history):
  return

"""## Gradio

### UI
"""

import gradio as gr

with gr.Blocks(theme="soft", css="body {zoom: 1.3;}") as demo:
    gr.Markdown("### 🥚 메추리알!! 성수/서울숲/건대 맛집 추천 챗봇")

    with gr.Row():
        mode_selector = gr.Radio(
            ["자율 검색형 (키워드)", "가이드라인형 (시나리오)"],
            label="사용 모드 선택",
            value="자율 검색형 (키워드)"
        )

    with gr.Row():
        chatbot = gr.Chatbot(height=500)

    with gr.Row():
        msg = gr.Textbox(label="질문 입력", scale=4)
        submit = gr.Button("전송", scale=1)
        reset_btn = gr.Button("새 대화 시작", scale=1)

    with gr.Accordion("분석 데이터", open=True):
        with gr.Tabs():
            with gr.TabItem("실시간 데이터"):
                with gr.Row():
                    pop_status_df = gr.Dataframe(label="실시간 인구데이터")
                    weather_df = gr.Dataframe(label="실시간 날씨데이터")

            with gr.TabItem("RAG 추천"):
                with gr.Row():
                    rag_retrieve_df = gr.Dataframe(label="1차: 리뷰 기반 추천 (Retrieve)")
                    rag_time_weight_df = gr.Dataframe(label="2차: 시의성 가중치 (Time Weight)")
                    rag_mmr_df = gr.Dataframe(label="3차: 다양성 확보 (MMR)")

            with gr.TabItem("메뉴 추천"):
                with gr.Row():
                    menu_attr_out = gr.Dataframe(label="추출된 메뉴 속성", col_count=(3, "fixed"))
                    menu_title_out = gr.Dataframe(label="메뉴 타이틀", col_count=(3, "fixed"))

    submit.click(
        fn=standard_run_query,
        inputs=[msg, chatbot],
        outputs=[chatbot, msg, pop_status_df, weather_df, rag_retrieve_df, rag_time_weight_df, rag_mmr_df, menu_attr_out, menu_title_out]
    )

    reset_btn.click(
        fn=reset_conversation,
        inputs=None,
        outputs=[chatbot, msg]
    )

demo.launch(share=True, debug=True, show_error=True)

"""## 사용자 입력




"""

# def run_query(_):
#     global chat_history

#     query = text_box.value.strip()
#     if query == "0":
#         print("END")
#         return chat_history

#     print(f"사용자 쿼리 : {query}\n")

#     retrieve_df, topk_df = recommend_reviews(query)

#     # mmr_df = select_reviews_mmr(query, lambda_mult=0.5, top_k=5, verbose=False)

#     select_df_menu, select_df_menu_title = recommend_menu(query)

#     answer = invoke_rag_chain(
#         retrieve_df,
#         topk_df,
#         # mmr_df,
#         select_df_menu,
#         select_df_menu_title,
#         query,
#         chat_history
#     )

#     print(answer)

#     return chat_history

# text_box = widgets.Text(
#     placeholder="검색어 (0 입력 시 종료)",
#     description="검색어 : ",
#     style={'description_width': 'initial'},
# )
# run_button = widgets.Button(description="BEGIN")

# run_button.on_click(run_query)

# display(text_box, run_button)

